name: GitOps

###
# GitOps - automatic infrastructure management GitHub Action
#
# See https://github.com/microsoft/NubesGen/blob/main/docs/gitops-overview.md
# for more information about using GitOps with NubesGen.
###

on:
  push:
    branches:
      - 'env-*'

jobs:
  manage-infrastructure:
    runs-on: ubuntu-20.04
    steps:
      - name: Apply Terraform configuration
        uses: jdubois/nubesgen-actions/gitops-apply-terraform@main
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          tf_storage_account: ${{ secrets.TF_STORAGE_ACCOUNT }}
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Build a Java project using Maven
        uses: jdubois/nubesgen-actions/gitops-build-java-maven@main
  deploy:
    needs: [manage-infrastructure, build]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy a Java application to Azure App Service
        uses: jdubois/nubesgen-actions/gitops-deploy-to-app-service-java@main
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
